#lang typed/racket/base
(require racket/list (only-in "domain.rkt" TokenDomain domain-member?))
(provide make-cars-trie cars-trie-root cars-trie-node-count cars-node-mass
         cars-node-domain-value cars-node-child-masses cars-node-check-domain!
         cars-node-child! make-cars-domain-update cars-commit!)
(define-type TokenId Natural)
(struct edge ([q : Real] [child : Node]) #:transparent)
(struct node ([mass : Real] [domain : (Option TokenDomain)] [domain-mass : Real]
              [removed : Real] [children : (HashTable TokenId edge)]
              [parent : (Option Node)] [parent-id : TokenId] [parent-q : Real])
  #:mutable #:transparent)
(define-type Node node)
(struct update ([node : Node] [domain : TokenDomain] [mass : Real]) #:transparent)
(define-type Update update)
(struct trie ([root : Node] [count : (Boxof Natural)]) #:transparent)
(define-type Trie trie)
(: make-cars-trie (-> Trie))
(define (make-cars-trie) (trie (node 1.0 #f 1.0 0.0 (make-hash) #f 0 0.0) (box 1)))
(: cars-trie-root (-> Trie Node))
(define cars-trie-root trie-root)
(: cars-trie-node-count (-> Trie Natural))
(define (cars-trie-node-count t) (unbox (trie-count t)))
(: cars-node-mass (-> Node Real))
(define cars-node-mass node-mass)
(: cars-node-domain-value (-> Node (Option TokenDomain)))
(define cars-node-domain-value node-domain)
(: make-cars-domain-update (-> Node TokenDomain Real Update))
(define make-cars-domain-update update)
(: cars-node-child-masses (-> Node (Listof (Pairof TokenId Real))))
(define (cars-node-child-masses n)
  (for/list : (Listof (Pairof TokenId Real)) ([(id e) (in-hash (node-children n))]
                                               #:unless (= 1.0 (node-mass (edge-child e))))
    (cons id (node-mass (edge-child e)))))
(: cars-node-child! (-> Trie Node TokenId Real Node))
(define (cars-node-child! t n id q)
  (define old (hash-ref (node-children n) id #f))
  (cond [old
         (unless (eqv? q (edge-q old)) (error 'cars "cached edge probability changed"))
         (edge-child old)]
        [else
         (define child (node 1.0 #f 1.0 0.0 (make-hash) n id q))
         (hash-set! (node-children n) id (edge q child))
         (set-box! (trie-count t) (add1 (unbox (trie-count t)))) child]))
(: cars-node-check-domain! (-> Node TokenDomain Real Void))
(define (cars-node-check-domain! n domain mass)
  (unless (and (equal? domain (node-domain n)) (eqv? mass (node-domain-mass n)))
    (error 'cars "cached frontier changed")))
(: clamp (-> Real Real))
(define (clamp x) (max 0.0 (min 1.0 x)))
(: install! (-> Node TokenDomain Real Void))
(define (install! n domain mass)
  (set-node-domain! n domain) (set-node-domain-mass! n (clamp mass))
  (define removed
    (for/fold ([total : Real 0.0]) ([(id e) (in-hash (node-children n))])
      (if (domain-member? domain id)
          (+ total (* (edge-q e) (- 1.0 (node-mass (edge-child e))))) total)))
  (set-node-removed! n removed) (set-node-mass! n (clamp (- (node-domain-mass n) removed))))
(: propagate! (-> Node Real Real Void))
(define (propagate! child old new)
  (define parent (node-parent child))
  (when parent
    (define domain (node-domain parent))
    (when (or (not domain) (domain-member? domain (node-parent-id child)))
      (define before (node-mass parent))
      (set-node-removed! parent (+ (node-removed parent) (* (node-parent-q child) (- old new))))
      (define after (clamp (- (if domain (node-domain-mass parent) 1.0) (node-removed parent))))
      (set-node-mass! parent after) (propagate! parent before after))))
(: cars-commit! (-> (Listof Update) (Option Node) Real Void))
(define (cars-commit! updates terminal terminal-mass)
  (for ([u (in-list updates)])
    (when (node-domain (update-node u)) (error 'cars "domain initialized twice")))
  (when (and terminal (> terminal-mass (+ (node-mass terminal) 1e-12)))
    (error 'cars "terminal mass exceeds envelope"))
  (define top (and (pair? updates) (update-node (last updates))))
  (define top-old (and top (node-mass top)))
  (define terminal-old (and terminal (node-mass terminal)))
  (when terminal (set-node-mass! terminal (clamp terminal-mass)))
  (for ([u (in-list updates)]) (install! (update-node u) (update-domain u) (update-mass u)))
  (cond [top (propagate! top (assert top-old real?) (node-mass top))]
        [terminal (propagate! terminal (assert terminal-old real?) (node-mass terminal))]))
