#lang racket/base
(require racket/list "program.rkt" "weak-json.rkt")
(provide make-observation observation? observation-schema observation-labels observation->datum
         datum->observation fit-calibration calibration-posterior calibration-posterior/row
         calibration-fingerprint calibration-diagnostics calibration-schema
         save-calibration load-calibration)
(struct observation (schema labels) #:transparent)
(struct calibration (schema source-arity selected prior bad good fingerprint diagnostics) #:transparent)
(struct fit (prior bad good objective iterations converged?) #:transparent)
(define (labels value [who 'weak-labels])
  (define xs (cond [(vector? value) (vector->list value)] [(list? value) value]
                   [else (raise-argument-error who "vector? or list?" value)]))
  (unless (andmap (lambda (x) (member x '(-1 0 1))) xs) (error who "invalid weak label"))
  (vector->immutable-vector (list->vector xs)))
(define (make-observation schema value)
  (unless (rule-schema? schema) (raise-argument-error 'make-observation "rule schema" schema))
  (define row (labels value 'make-observation))
  (unless (= (vector-length row) (length (rule-schema-rule-ids schema))) (error 'make-observation "label width does not match rule schema"))
  (unless (for/and ([x (in-vector row)] [polarity (in-list (rule-schema-polarities schema))])
            (or (zero? x) (= x polarity)))
    (error 'make-observation "label contradicts declared rule polarity"))
  (observation schema row))
(define (observation->datum o)
  (unless (observation? o) (raise-argument-error 'observation->datum "observation?" o))
  (hash 'format "rack-llm-observation" 'version 1 'schema (rule-schema->datum (observation-schema o))
        'labels (vector->list (observation-labels o))))
(define (datum->observation value)
  (unless (hash? value) (raise-argument-error 'datum->observation "observation object" value))
  (define (field key) (hash-ref value key (lambda () (error 'datum->observation "missing ~a" key))))
  (unless (and (equal? (field 'format) "rack-llm-observation") (equal? (field 'version) 1)) (error 'datum->observation "unsupported observation format or version"))
  (make-observation (datum->rule-schema (field 'schema)) (field 'labels)))
(define (clamp x) (max 1e-12 (min (- 1.0 1e-12) x)))
(define (sigmoid x) (if (>= x 0.0) (/ 1.0 (+ 1.0 (exp (- x))))
                        (let ([e (exp x)]) (/ e (+ 1.0 e)))))
(define (label-index x) (case x [(-1) 0] [(0) 1] [(1) 2]))
(define (probability ps x) (vector-ref ps (label-index x)))
(define (normalize counts total) (for/vector ([x (in-vector counts)]) (clamp (/ x total))))
(define (mean ps) (- (vector-ref ps 2) (vector-ref ps 0)))
(define (evaluate rows prior bad good)
  (define responsibilities (make-vector (length rows) 0.5))
  (define objective 0.0)
  (for ([row (in-list rows)] [k (in-naturals)])
    (define l0 (+ (log (- 1.0 prior)) (for/sum ([x (in-vector row)] [p (in-vector bad)]) (log (probability p x)))))
    (define l1 (+ (log prior) (for/sum ([x (in-vector row)] [p (in-vector good)]) (log (probability p x)))))
    (define top (max l0 l1))
    (set! objective (+ objective top (log (+ (exp (- l0 top)) (exp (- l1 top))))))
    (vector-set! responsibilities k (sigmoid (- l1 l0))))
  (values objective responsibilities))
(define (fit-once rows limit tolerance pseudocount separation rng)
  (define n (length rows)) (define m (vector-length (car rows)))
  (define prior (parameterize ([current-pseudo-random-generator rng])
                  (sigmoid (* 0.25 (- (* 2.0 (random)) 1.0)))))
  (define bad (for/vector ([_ (in-range m)]) (vector 0.25 0.5 0.25)))
  (define good (for/vector ([_ (in-range m)]) (vector 0.25 0.5 0.25)))
  (for ([i (in-range m)])
    (define counts (vector pseudocount pseudocount pseudocount))
    (for ([row (in-list rows)])
      (define j (label-index (vector-ref row i))) (vector-set! counts j (add1 (vector-ref counts j))))
    (define base (normalize counts (+ n (* 3.0 pseudocount))))
    (define tilt (+ separation (parameterize ([current-pseudo-random-generator rng])
                                (* 0.25 (- (* 2.0 (random)) 1.0)))))
    (for ([target (in-list (list good bad))] [sign (in-list '(1.0 -1.0))])
      (define raw (for/vector ([p (in-vector base)] [x (in-list '(-1.0 0.0 1.0))])
          (* p (exp (* sign tilt x)))))
      (vector-set! target i (normalize raw (for/sum ([x (in-vector raw)]) x)))))
  (let loop ([iteration 0] [prior prior] [bad bad] [good good] [previous -inf.0])
    (define-values (objective responsibilities) (evaluate rows prior bad good))
    (define converged? (and (> iteration 0) (<= (/ (abs (- objective previous)) (max 1.0 (abs previous))) tolerance)))
    (cond [(or converged? (>= iteration limit) (< objective (- previous 1e-8)))
           (fit prior bad good objective iteration converged?)]
          [else
           (define good-total (for/sum ([x (in-vector responsibilities)]) x)) (define bad-total (- n good-total))
           (define next-bad (for/vector ([_ (in-range m)]) (vector 0.25 0.5 0.25)))
           (define next-good (for/vector ([_ (in-range m)]) (vector 0.25 0.5 0.25)))
           (for ([i (in-range m)])
             (define bad-counts (vector pseudocount pseudocount pseudocount))
             (define good-counts (vector pseudocount pseudocount pseudocount))
             (for ([row (in-list rows)] [weight (in-vector responsibilities)])
               (define j (label-index (vector-ref row i)))
               (vector-set! good-counts j (+ (vector-ref good-counts j) weight))
               (vector-set! bad-counts j (+ (vector-ref bad-counts j) (- 1.0 weight))))
             (define b (normalize bad-counts (+ bad-total (* 3.0 pseudocount))))
             (define g (normalize good-counts (+ good-total (* 3.0 pseudocount))))
             (if (< (mean g) (mean b))
                 (let* ([pooled (for/vector ([x (in-vector bad-counts)]
                                             [y (in-vector good-counts)]) (+ x y))]
                        [neutral (normalize pooled (+ n (* 6.0 pseudocount)))])
                   (vector-set! next-bad i neutral)
                   (vector-set! next-good i neutral))
                 (begin (vector-set! next-bad i b) (vector-set! next-good i g))))
           (loop (add1 iteration)
                 (clamp (/ (+ good-total pseudocount) (+ n (* 2.0 pseudocount))))
                 next-bad next-good objective)])))
(define (same-column? rows a b) (andmap (lambda (row) (= (vector-ref row a) (vector-ref row b))) rows))
(define (projection rows width)
  (define selected '()) (define constants '()) (define duplicates '())
  (for ([i (in-range width)])
    (define values (remove-duplicates (map (lambda (row) (vector-ref row i)) rows)))
    (cond [(= (length values) 1) (set! constants (append constants (list i)))]
          [(for/first ([kept (in-list selected)] #:when (same-column? rows i kept)) kept)
           => (lambda (kept)
                (set! duplicates (append duplicates (list (hash 'slot i 'duplicate-of kept)))))]
          [else (set! selected (append selected (list i)))]))
  (values selected constants duplicates))
(define (project row selected)
  (vector->immutable-vector (list->vector (map (lambda (i) (vector-ref row i)) selected))))
(define (calibration-form schema selected prior bad good)
  (list 'rack-llm-calibration 1 (rule-schema-fingerprint schema) selected prior
        (vector->list bad) (vector->list good)))
(define (fit-calibration source [strings #f] #:max-iterations [limit 200] #:tolerance [tolerance 1e-5]
                         #:pseudocount [pseudocount 1.0] #:restarts [restarts 32]
                         #:seed [seed 0])
  (define observations
    (cond [(rule-set? source)
           (unless (and (list? strings) (pair? strings) (andmap string? strings)) (raise-argument-error 'fit-calibration "non-empty list of strings" strings))
           (define schema (rule-set-schema source))
           (map (lambda (text) (make-observation schema (rule-set-observe source text))) strings)]
          [strings (error 'fit-calibration "second positional argument requires a rule-set")]
          [else source]))
  (unless (and (pair? observations) (andmap observation? observations)) (raise-argument-error 'fit-calibration "non-empty list of observations" observations))
  (define schema (observation-schema (car observations)))
  (unless (andmap (lambda (o) (equal? schema (observation-schema o))) observations) (error 'fit-calibration "observations use different rule schemas"))
  (define source-rows (map observation-labels observations))
  (define source-arity (length (rule-schema-rule-ids schema)))
  (define-values (selected constants duplicates) (projection source-rows source-arity))
  (when (< (length selected) 3) (error 'fit-calibration "unidentifiable calibration after constant/duplicate projection"))
  (define rows (map (lambda (row) (project row selected)) source-rows))
  (define fits
    (for/list ([restart (in-range restarts)])
      (define rng (make-pseudo-random-generator))
      (parameterize ([current-pseudo-random-generator rng]) (random-seed (add1 (abs (+ seed restart)))))
      (fit-once rows limit tolerance pseudocount (+ 0.75 (* 0.05 restart)) rng)))
  (define converged (filter fit-converged? fits))
  (when (null? converged) (error 'fit-calibration "no EM restart converged"))
  (define best (argmax fit-objective converged))
  (define active
    (for/sum ([b (in-vector (fit-bad best))] [g (in-vector (fit-good best))])
      (if (>= (for/sum ([x (in-vector b)] [y (in-vector g)]) (abs (- y x))) 1e-3) 1 0)))
  (when (< active 3) (error 'fit-calibration "unidentifiable calibration: fitted solution collapsed"))
  (define form (calibration-form schema selected (fit-prior best) (fit-bad best) (fit-good best)))
  (define ids (rule-schema-rule-ids schema)) (define polarities (rule-schema-polarities schema))
  (define active-ids
    (for/list ([slot (in-list selected)] [b (in-vector (fit-bad best))] [g (in-vector (fit-good best))]
               #:when (>= (for/sum ([x (in-vector b)] [y (in-vector g)]) (abs (- y x))) 1e-3))
      (list-ref ids slot)))
  (define weights
    (for/hash ([slot (in-list selected)] [b (in-vector (fit-bad best))]
               [g (in-vector (fit-good best))])
      (define fire (list-ref polarities slot))
      (values (string->symbol (list-ref ids slot))
              (- (log (/ (probability g fire) (probability b fire)))
                 (log (/ (probability g 0) (probability b 0)))))))
  (define dropped
    (append (for/list ([slot (in-list constants)])
              (hash 'rule-id (list-ref ids slot) 'source-slot slot 'reason "constant"))
            (for/list ([duplicate (in-list duplicates)])
              (define slot (hash-ref duplicate 'slot)) (define kept (hash-ref duplicate 'duplicate-of))
              (hash 'rule-id (list-ref ids slot) 'source-slot slot 'reason "exact-duplicate"
                    'duplicate-of-rule-id (list-ref ids kept) 'duplicate-of-source-slot kept))))
  (calibration
   schema source-arity selected (fit-prior best) (fit-bad best) (fit-good best) (datum-fingerprint form)
   (hash 'iterations (fit-iterations best) 'objective (fit-objective best)
         'observations (length rows) 'source-rules source-arity 'fitted-rules (length selected)
         'selected-source-slots selected 'constant-source-slots constants
         'duplicate-source-slots duplicates 'dropped-rules dropped 'rule-weights weights 'active-rules active
         'active-rule-ids active-ids 'neutralized-rules (- (length selected) active)
         'neutralized-rule-ids (remove* active-ids (map (lambda (slot) (list-ref ids slot)) selected)))))
(define (calibration-posterior/row model value)
  (define row (labels value 'calibration-posterior/row))
  (unless (= (vector-length row) (calibration-source-arity model)) (error 'calibration-posterior/row "label width does not match calibration schema"))
  (define projected (project row (calibration-selected model)))
  (sigmoid
   (+ (log (/ (calibration-prior model) (- 1.0 (calibration-prior model))))
      (for/sum ([x (in-vector projected)] [b (in-vector (calibration-bad model))]
                [g (in-vector (calibration-good model))])
        (log (/ (probability g x) (probability b x)))))))
(define (calibration-posterior model value)
  (unless (observation? value) (raise-argument-error 'calibration-posterior "observation?" value))
  (unless (equal? (calibration-schema model) (observation-schema value)) (error 'calibration-posterior "observation rule schema does not match calibration"))
  (calibration-posterior/row model (observation-labels value)))
(define (json-safe x)
  (cond [(and (real? x) (exact? x)) (exact->inexact x)]
        [(hash? x) (for/hash ([(k v) (in-hash x)]) (values k (json-safe v)))]
        [(vector? x) (map json-safe (vector->list x))]
        [(list? x) (map json-safe x)] [else x]))
(define (save-calibration model path)
  (write-json-file
   (hash 'format "rack-llm-calibration" 'version 1
         'schema (rule-schema->datum (calibration-schema model))
         'selected_source_slots (calibration-selected model)
         'prior_good (calibration-prior model)
         'p_label_bad (json-safe (calibration-bad model))
         'p_label_good (json-safe (calibration-good model))
         'diagnostics (json-safe (calibration-diagnostics model))
         'fingerprint (calibration-fingerprint model))
   path))
(define (probability-matrix who value)
  (unless (list? value) (raise-argument-error who "probability matrix" value))
  (for/vector ([row (in-list value)])
    (unless (and (list? row) (= (length row) 3) (andmap real? row))
      (raise-argument-error who "rows of three probabilities" row))
    (define result (list->vector row))
    (unless (and (andmap (lambda (x) (and (> x 0.0) (< x 1.0))) row)
                 (<= (abs (- (for/sum ([x (in-vector result)]) x) 1.0)) 1e-8))
      (error who "invalid probability row"))
    result))
(define (load-calibration path)
  (define payload (read-json-file path))
  (unless (hash? payload) (error 'load-calibration "calibration file is not a JSON object"))
  (define (field key) (hash-ref payload key (lambda () (error 'load-calibration "missing ~a" key))))
  (unless (and (equal? (field 'format) "rack-llm-calibration") (equal? (field 'version) 1)) (error 'load-calibration "unsupported calibration format or version"))
  (define schema (datum->rule-schema (field 'schema)))
  (define source-arity (length (rule-schema-rule-ids schema)))
  (define selected (field 'selected_source_slots))
  (unless (and (list? selected) (>= (length selected) 3)
               (andmap exact-nonnegative-integer? selected)
               (equal? selected (sort (remove-duplicates selected) <))
               (andmap (lambda (slot) (< slot source-arity)) selected))
    (error 'load-calibration "invalid source projection"))
  (define prior (field 'prior_good))
  (define bad (probability-matrix 'load-calibration (field 'p_label_bad)))
  (define good (probability-matrix 'load-calibration (field 'p_label_good)))
  (unless (and (real? prior) (> prior 0.0) (< prior 1.0)
               (= (length selected) (vector-length bad) (vector-length good)))
    (error 'load-calibration "inconsistent calibration dimensions"))
  (for ([b (in-vector bad)] [g (in-vector good)])
    (when (< (mean g) (mean b)) (error 'load-calibration "signed orientation violation")))
  (define fp (datum-fingerprint (calibration-form schema selected prior bad good)))
  (unless (equal? fp (field 'fingerprint)) (error 'load-calibration "calibration fingerprint mismatch"))
  (define diagnostics (field 'diagnostics))
  (calibration schema source-arity selected prior bad good fp
               (if (hash? diagnostics) diagnostics (hash))))
