name: experiments-static

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: Bogdanp/setup-racket@v1.14
        with:
          version: stable
      - run: sudo apt-get update && sudo apt-get install -y build-essential libpcre2-dev zstd
      - run: raco pkg install --auto --name rack-llm --link "$PWD"
      - run: make -C experiments static-ci
